
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 26 04:06:49 ICT 2018
//----------------------------------------------------

package rcalc.parsers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int DIVIDE = 5;
  public static final int MULTIPLY = 4;
  public static final int NUMBER = 9;
  public static final int PLUS = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int LPAREN = 7;
  public static final int EXP = 6;
}

